---
name: esp-idf ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: release-v4.4
          target: esp32s3
          path: firmware

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            firmware/build/firmware.bin
            firmware/build/firmware.elf
          if-no-files-found: error

      - name: rename and checksum firmware
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd firmware/build
          sudo install -d -o "$USER" release
          cd release
          cp -v "../firmware.bin" "roomsense_${{ github.ref_name }}.bin"
          cp -v "../firmware.elf" "roomsense_${{ github.ref_name }}.elf"
          sha256sum *.bin *.elf | tee SHA256SUMS.txt

      - name: publish firmware release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          preserve_order: true
          fail_on_unmatched_files: true
          files: |
            firmware/build/release/*.bin
            firmware/build/release/*.elf
            firmware/build/release/*.txt
